package com.mappilot.export

import com.mappilot.core.model.Landmark
import java.io.OutputStream
import java.nio.ByteBuffer
import java.nio.ByteOrder

/**
 * One exported point: position (metres, the geo/world frame chosen by the caller)
 * plus a 0..1 confidence used as an intensity/scalar field.
 */
data class ExportPoint(val x: Double, val y: Double, val z: Double, val confidence: Float)

internal fun List<Landmark>.toExportPoints(useGeo: Boolean): List<ExportPoint> = mapNotNull { l ->
    if (useGeo) {
        val g = l.geo ?: return@mapNotNull null
        ExportPoint(g.longitude, g.latitude, g.altitude, l.confidence)
    } else {
        ExportPoint(l.position.x, l.position.y, l.position.z, l.confidence)
    }
}

/**
 * PLY writer (Stanford polygon format). Emits `x,y,z` floats plus a `confidence`
 * scalar field that CloudCompare/MeshLab display. ASCII for portability; binary
 * little-endian for size. Pure — round-tripped in unit tests and validated by the
 * reference tooling.
 */
object PlyWriter {

    fun writeAscii(out: OutputStream, points: List<ExportPoint>) {
        val w = out.bufferedWriter()
        w.write(header("ascii", points.size))
        for (p in points) {
            w.write("${p.x.toFloat()} ${p.y.toFloat()} ${p.z.toFloat()} ${p.confidence}\n")
        }
        w.flush()
    }

    fun writeBinaryLittleEndian(out: OutputStream, points: List<ExportPoint>) {
        out.write(header("binary_little_endian", points.size).toByteArray(Charsets.US_ASCII))
        val buf = ByteBuffer.allocate(points.size * 16).order(ByteOrder.LITTLE_ENDIAN)
        for (p in points) {
            buf.putFloat(p.x.toFloat()); buf.putFloat(p.y.toFloat())
            buf.putFloat(p.z.toFloat()); buf.putFloat(p.confidence)
        }
        out.write(buf.array())
        out.flush()
    }

    private fun header(format: String, count: Int): String = buildString {
        append("ply\n")
        append("format $format 1.0\n")
        append("comment Generated by MapPilot\n")
        append("element vertex $count\n")
        append("property float x\n")
        append("property float y\n")
        append("property float z\n")
        append("property float confidence\n")
        append("end_header\n")
    }
}

/**
 * PCD writer (Point Cloud Library, v0.7). Fields `x y z intensity`; intensity is
 * the confidence. ASCII and binary forms both open in CloudCompare/PCL tools.
 */
object PcdWriter {

    fun writeAscii(out: OutputStream, points: List<ExportPoint>) {
        val w = out.bufferedWriter()
        w.write(header("ascii", points.size))
        for (p in points) {
            w.write("${p.x.toFloat()} ${p.y.toFloat()} ${p.z.toFloat()} ${p.confidence}\n")
        }
        w.flush()
    }

    fun writeBinary(out: OutputStream, points: List<ExportPoint>) {
        out.write(header("binary", points.size).toByteArray(Charsets.US_ASCII))
        val buf = ByteBuffer.allocate(points.size * 16).order(ByteOrder.LITTLE_ENDIAN)
        for (p in points) {
            buf.putFloat(p.x.toFloat()); buf.putFloat(p.y.toFloat())
            buf.putFloat(p.z.toFloat()); buf.putFloat(p.confidence)
        }
        out.write(buf.array())
        out.flush()
    }

    private fun header(data: String, count: Int): String = buildString {
        append("# .PCD v0.7 - Point Cloud Data file format\n")
        append("VERSION 0.7\n")
        append("FIELDS x y z intensity\n")
        append("SIZE 4 4 4 4\n")
        append("TYPE F F F F\n")
        append("COUNT 1 1 1 1\n")
        append("WIDTH $count\n")
        append("HEIGHT 1\n")
        append("VIEWPOINT 0 0 0 1 0 0 0\n")
        append("POINTS $count\n")
        append("DATA $data\n")
    }
}
